{{- $top := . -}}
{{- range $application :=  .Values.applications -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-app1
    server: {{ $application.server }}
  project: default
  source:
    path: helm-guestbook
    repoURL: {{ $application.repoURL }}
    targetRevision: {{ $application.targetRevision }}
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true
{{ end }}
